### PR TITLE
SGcommit

### PR DESCRIPTION
**Pull request by jakubmuransky**

### CODE REVIEW

**Comment by sfonteneau** [comment]
@jakubmuransky 

I think there is a problem in this code.

if there is no group in the conf then:
`group = samdb_loc.get_default_basedn()`

but no one has a member of "dc=mydomain,dc=lan"
`user_filter = f"(&(objectClass=user)(memberOf={group}))"`

In this case, you should not put memberof in the filter.

Another note, you can use the filter with the oid to support nested groups:

`(memberof:1.2.840.113556.1.4.1941:=CN=group_users,OU=Groupe,DC=mydomain,DC=lan)`

**Comment by jakubmuransky** [comment]
Hello, thanks for the comment. I made a local fork for this. 
That's the reason why I close the MR. 
I'm not a programmer, could you add a support for groups there ? It's good to specify group for tests or early deployment not for whole domain, in previous setup when I put CN of the group to the base it didn't work.

**Comment by sfonteneau** [comment]
I added an ldap filter parameter which allows more flexibility (for a group filter for example):
https://github.com/sfonteneau/samba4-gaps/blob/master/gaps.conf.template#L13

I also added the "mail_attribute" option in case the mail is not the mail attribute.

I also took the opportunity to put the logs in json format (for SIEM)

**Comment by jakubmuransky** [comment]
Hello, 
I finally pulled your master, it looks fine but I'm getting error about google cache.
`}
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/lib/python3/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 40, in <module>
    raise ImportError(
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth`

**Comment by sfonteneau** [comment]
it seems to come from the google library. unfortunately I no longer have a google apps account to do the test, I will try to create a trial one to see.

**Pull request closed without merging**
